# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_color_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('colors', models.ManyToManyField(to='api.Color')),
            ],
        ),
    ]
